In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7], [1,2,3,4,5,6,7]])

In [4]:
a[1,1]

2

In [5]:
a[:] = 1

In [6]:
a

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [15]:
 a = np.full((5,5,6), [1,2,3,4,5,6])

In [16]:
print(a)

[[[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]]


In [20]:
a = np.ones((5,5))
a[1:4,1:4] = 0
a[2,2] = 9

In [22]:
a * [1,1,1]

ValueError: operands could not be broadcast together with shapes (5,5) (3,) 

In [34]:
a = np.array([[1, 0], [0,0]])
b = a[:, :, np.newaxis] * np.ones((2,2,3))


In [35]:
b

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
color_buckets = np.array([[0,0,0], [1,1,1]])
color_buckets = np.where(color_buckets == [0,0,0], np.array([155,188,15]),color_buckets)

In [45]:
color_buckets

array([[155, 188,  15],
       [  1,   1,   1]])