In [1]:
import numpy as np

In [4]:
zeros = np.zeros((5,5))

In [13]:
identity = np.identity(5)

In [17]:
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
impulse = np.zeros((5,5))
impulse[1:4,1:4] = 1
impulse[2,2] = 2
impulse

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 2., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [110]:
def generate_kernal(kernal_size, increment_function):
    side_length = kernal_size * 2 + 1
    m = np.zeros((side_length, side_length))
    sub_matrix_side_length = side_length
    x = 0
    y = 0
    v = 1
    while sub_matrix_side_length > 0:
        m[
            x:side_length-x,
            y:side_length-y
        ] = increment_function(v)
        x += 1
        y += 1
        v += 1
        sub_matrix_side_length -= (0.5)
    return m
        
    

In [154]:
# kernal = generate_kernal(kernal_size=1, increment_function=lambda x: 1)
kernal = np.zeros((3,3))
kernal[1,1] =1
kernal

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [155]:
image = np.ones((5,5))
image

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
for i in range(1,4):
    for j in range(1,4):
        print(i,j)
        image[i,j] = np.sum(image[i-1:i+2, j-1:j+2] * kernal) / len(kernal)

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3


In [157]:
image

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 0.33333333, 0.33333333, 0.33333333, 1.        ],
       [1.        , 0.33333333, 0.33333333, 0.33333333, 1.        ],
       [1.        , 0.33333333, 0.33333333, 0.33333333, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [158]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
for i in range(0,3):
    x[i] = i

In [185]:
output = np.array([[4,5,6],[7,8,9]])

In [186]:
output

array([[4, 5, 6],
       [7, 8, 9]])

In [194]:
y = np.append(output, np.array([[10,11,12]]), axis=0)

In [195]:
y

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [257]:
image = np.array([[ 4,  0,  6],
       [ 7,  5,  9],
       [1, 2, 0]])
image

array([[4, 0, 6],
       [7, 5, 9],
       [1, 2, 0]])

In [266]:
y = np.zeros((2,3))
for row_index in range(0,len(image) - 1):
    y[row_index] = image[row_index + 1, :] - image[row_index, :]
    

In [267]:
x = np.zeros((2,3))
for column_index in range(0,len(image) - 1):
    x[column_index] = image[:, column_index + 1] - image[:, column_index]
    

In [294]:
subset_y = y[0:2, 0:2]
subset_y

array([[ 3.,  5.],
       [-6., -3.]])

In [295]:
subset_x = x.T[0:2, 0:2]
subset_x

array([[-4.,  6.],
       [-2.,  4.]])

In [296]:
magnitude = (subset_x ** 2 + subset_y ** 2) ** 0.5

In [297]:
magnitude

array([[5.        , 7.81024968],
       [6.32455532, 5.        ]])

In [298]:
x.shape

(2, 3)

In [299]:
y.shape

(2, 3)